# Generated by Django 4.2.7 on 2026-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, unique=True)),
                ('game_type', models.CharField(choices=[('TIC_TAC_TOE', 'Tic Tac Toe'), ('LUDO', 'Ludo')], default='TIC_TAC_TOE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_state', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
