# Generated by Django 4.2.7 on 2026-02-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.CharField(default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='player_count',
            field=models.IntegerField(default=2),
        ),
    ]
